name: "Check Merge"

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-24.04
    permissions:
      security-events: write
      contents: read
      actions: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Build and test all targets explicitly requesting the 'static_analysis'
      # output group so that SARIF files are generated.
      - name: Build & Test
        id: build-and-test
        run: bazel test --color=yes //... --output_groups=+static_analysis

      # The Github action 'github/codeql-action/upload-sarif' chokes with
      # symlinks pointing to directories (e.g. bazel-bin). So, we copy the
      # SARIF files to a temporary directory and upload them from there.
      - name: Collect SARIF files
        id: collect-sarif-files
        if: "!cancelled()"
        run: |
          find bazel-bin/ -name "*.sarif" -exec cp --parents --target-directory="${{ runner.temp }}" {} +
          echo "count=$(find "${{ runner.temp}}/bazel-bin" 2> /dev/null | wc -l)" >> "${GITHUB_OUTPUT}"

      - name: Upload SARIF files
        id: upload-sarif-files
        uses: github/codeql-action/upload-sarif@v3
        if: "!cancelled() && steps.collect-sarif-files.outputs.count > 0"
        with:
          # Search and upload any '.sarif' files under "${{ runner.temp }}/bazel-bin".
          sarif_file: "${{ runner.temp }}/bazel-bin"
          category: "some-category"
